# Sets up the app localization generation
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# Make the AppLocalizations.of(context) not need a null check
nullable-getter: false
